name: Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: 'src/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./src
      run: |
        npm install
        npm install --save-dev cross-env
      
    - name: Verify server startup
      working-directory: ./src
      run: |
        npm run mode:prod | grep -m 1 "App running on port" && echo "✅ Server verification completed successfully!"